apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-REPLACE_ME
  directoryPerms: "750"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
mountOptions:
  - tls
reclaimPolicy: Retain
volumeBindingMode: Immediate
