apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deposition-demo

resources:
  - namespace.yaml
  - api-configmap.yaml
  - api-secret.yaml
  - couchdb-secret.yaml
  - efs-storageclass.yaml
  - deposition-pvc.yaml
  - couchdb-service.yaml
  - couchdb-statefulset.yaml
  - ollama-pvc.yaml
  - ollama-service.yaml
  - ollama-deployment.yaml
  - api-service.yaml
  - api-deployment.yaml
  - ingress.yaml
  - ollama-model-loader-job.yaml
